### Get all people
GET http://localhost:3001/api/people

### Get info
GET http://localhost:3001/info

### Get a person
GET http://localhost:3001/api/people/5

### Delete a person
DELETE http://localhost:3001/api/people/1

### Post a person
POST http://localhost:3001/api/people
Content-Type: application/json

{
  "name": "Test Testburg",
  "number": "123123123"
}